#!/usr/bin/env bash

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

echo "安装wget"
yum -y install wget

wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz

tar vzfx Python-3.6.5.tgz

cd Python-3.6.5

yum groupinstall -y "Development tools"

./configure

make

make install
